/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LiveRouteImport } from './routes/live'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRssRouteImport } from './routes/api/rss'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRssRoute = ApiRssRouteImport.update({
  id: '/api/rss',
  path: '/api/rss',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/discover': typeof DiscoverRoute
  '/live': typeof LiveRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/rss': typeof ApiRssRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/discover': typeof DiscoverRoute
  '/live': typeof LiveRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/rss': typeof ApiRssRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/discover': typeof DiscoverRoute
  '/live': typeof LiveRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/rss': typeof ApiRssRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/discover'
    | '/live'
    | '/sitemap.xml'
    | '/api/rss'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connect' | '/discover' | '/live' | '/sitemap.xml' | '/api/rss'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/discover'
    | '/live'
    | '/sitemap.xml'
    | '/api/rss'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  DiscoverRoute: typeof DiscoverRoute
  LiveRoute: typeof LiveRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiRssRoute: typeof ApiRssRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rss': {
      id: '/api/rss'
      path: '/api/rss'
      fullPath: '/api/rss'
      preLoaderRoute: typeof ApiRssRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  DiscoverRoute: DiscoverRoute,
  LiveRoute: LiveRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiRssRoute: ApiRssRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
